[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloy = { workspace = true }
tokio = { workspace = true }
alloy-chains = { workspace = true }
eyre = { workspace = true }
alloy-primitives = { workspace = true }

shared = { path = "../../crates/shared" }
config = { path = "../../crates/config" }
generalized-arb-strategy = { path = "../../crates/strategies/generalized-arb" }
types = { path = "../../crates/types" }
engine = { path = "../../crates/engine" }
addressbook = { path = "../../crates/addressbook" }
provider = { path = "../../crates/provider" }
amms = { path = "../../crates/amms" }
tx-executor = { path = "../../crates/tx-executor" }
codex-client = { path = "../../crates/codex-client" }
pool-manager = { path = "../../crates/pool-manager" }

anyhow = "1.0.70"
clap = { version = "4.2.5", features = ["derive"] }
dotenv = "0.15.0"
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
